### ISSUE TITLE
Possible new feature? (Kanjidict support)

### ISSUE THREAD

**Issue by naomi789** [tkshnwesper/JMdict-Parser#7]
I love this so much!! I was wondering if you've thought about adding the functionality to deal with Jim Breen's KanjiDict? The XML has a lot in common (I just find json so much easier to deal with). 

https://www.edrdg.org/wiki/index.php/KANJIDIC_Project

**Comment by smachave** [comment]
Hey Naomi!

It appears that [fast-xml-parser](https://www.npmjs.com/package/fast-xml-parser) is able to parse KANJIDICT without additional configuration.

```
npm install fast-xml-parser -g

fast-xml-parser path_to_kanjidict_file > output.json
```

It would create something like [this](https://send.firefox.com/download/3908df321fc4347c/#CONtsfHqZyRbKHTDR5_WvQ) but with whitespaces.

Cheers!

**Comment by naomi789** [comment]
You're right! That worked wonders, thank you :)
