### ISSUE TITLE
No file created

### ISSUE THREAD

**Issue by pnewell** [tkshnwesper/JMdict-Parser#8]
I am running on a Mac, and despite getting the "Your JSON file is saved at" message, the file is no where to be found.

**Comment by smachave** [comment]
Hello @pnewell, thanks for reporting this issue. I'm trying to reproduce your scenario. Which JMdict file did you use, was it the one with only the English glosses or the full JMdict file?

Also did you run the application on the extracted file?

**Comment by pnewell** [comment]
I was using edict2, didn't realize it only works with JMdict, feel free to close, sorry!
