### ISSUE TITLE
Advantage of using this tool instead of generic XML to JSON converters?

### ISSUE THREAD

**Issue by echamudi** [tkshnwesper/JMdict-Parser#9]
There are some already available tools like the `xml2json` converter that also can convert JMdict XML into JSON by simply:
```
npm -g xml2json  xml2json-cli
xml2json ./JMdict_e ./JMdict_e.json
```
Also in the tool above, there are [many options](https://www.npmjs.com/package/xml2json) that we can configure for the conversion.

What are the advantages of this tool for being exclusive as a JMdict parser, compared to the method above using generic XML to JSON converter?

**Comment by smachave** [comment]
That's a fair point. At the time when I needed this functionality, these other libraries did not come under my radar, so I used what was available and made a tool.

But you are right, there is no real necessity of this tool as generic converters would do the trick just as well.
